### ISSUE TITLE
General survival stuff

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/autosurvive#20]
Obviously a lot of crafting/survival stuff still needs to be done, but that's a thing to figure out once more systems are in place. Will close this issue when the game loop is finalised.

**Comment by TerryCavanagh** [comment]
Ok, I feel far enough along now to start working on this. Getting slightly worried about falling into a trap of just adding more and more systems, heh. Will start into it on Monday

**Comment by TerryCavanagh** [comment]
This issue had kind of a big scope, but I've finally gotten the game to generate complete worlds, and it's now possible to just sit down and play it, even if there are gaps and balance issues. Closing this and moving on! I'll open new issues for specific remaining problems.

**Comment by randomnine** [comment]
really cool! I'm hyped :D
