### ISSUE TITLE
Fix broken auto-equip

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/autosurvive#55]
You used to automatically equip the item you were crafting if it was a tool if you had nothing equipped, this is currently broken

**Comment by randomnine** [comment]
I set it up yesterday to auto-equip tools and placeable stuff (like beds, workbenches) after crafting them - see 92c6b1a3a42d66cf77ff2c215bec37c7b903cfa2

**Comment by TerryCavanagh** [comment]
Oh, yep, you've totally fixed this! Nice :)
