### ISSUE TITLE
Use distinct names for blocks and items

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/autosurvive#62]
World.hx:79: Checking for itemname collision
World.hx:83: ERROR:	"stone" refers to both a block and an item
World.hx:83: ERROR:	"wood" refers to both a block and an item
World.hx:83: ERROR:	"mushroom" refers to both a block and an item
World.hx:83: ERROR:	"workbench" refers to both a block and an item
World.hx:83: ERROR:	"sawmill" refers to both a block and an item
World.hx:83: ERROR:	"fence" refers to both a block and an item
World.hx:83: ERROR:	"chair" refers to both a block and an item
World.hx:83: ERROR:	"electronicsbench" refers to both a block and an item
World.hx:83: ERROR:	"bed" refers to both a block and an item
World.hx:83: ERROR:	"shelter" refers to both a block and an item
World.hx:83: ERROR:	"chest" refers to both a block and an item
World.hx:83: ERROR:	"kiln" refers to both a block and an item
World.hx:83: ERROR:	"wheat" refers to both a block and an item

**Comment by TerryCavanagh** [comment]
So I'm not 100% sure of the best approach to fixing this. I can think of different cases where I'd want it to behave in different ways:

```
moveto(wood);
```

I'd want that to move to a loose wood item instead of a placed floorboard for sure. Probably the solution here is to call the placed wood block "floorboard", or something.

```
moveto(workbench);
```

I'd definitely want that to move to a placed workbench rather than scan the entire map for a loose workbench item. However:

```
collect(workbench);
```

I'd definitely want that to refer to the floating item.

Maybe the solution is to be context sensitive? moveto() could always refer to a block, and e.g. find() could always refer to an item. Or is that just more complicated? Ahh, dunno, just thinking out loud.

**Comment by randomnine** [comment]
I think we should disambiguate this stuff on a case by case basis as far as possible and see how far we can get.

Most of the problems are with constructable heavy items, like the workbench or bed. Could we prevent these from becoming free-floating items entirely? i.e. dropping a heavy item means the same thing as placing it, and breaking up a heavy item with a hammer breaks it into components instead of making it a free-floating item for transport.

Mushrooms and wheat seem like the toughest. For wheat, we could introduce a processing step in harvesting - so "wheat" from a field is automatically reduced to "grain".

**Comment by TerryCavanagh** [comment]
Yep on all three! Ok, so I'll change 

stone -> rock
wood -> floorboard

electronicsbench, bed, shelter, chest, workbench, sawmill and kiln can all have a new behavior where they have no intermediate dropped item state - whoever crafts it carrys it

That leaves mushroom, fence, chair and wheat, which are more tricky. Hmm.

Ok, yep, the individual wheat stalks could be called grain, that's good.

Maybe mushrooms should just go - there's quite a lot of food in the game at this point, and blackberries basically serve the same design purpose

chair and fence, idk. I guess I could just classify them as heavy items too, though that does make dismantling a house and moving stuff a lot more work. Will leave it for now.

**Comment by TerryCavanagh** [comment]
Ok, thinking about this a bit more, I like the behaviour of heavy items having the same in-between floating state as other items. Hitting a workbench with a hammer probably shouldn't equip the workbench, for example.

All the remaining problem entities are either bulky items like this, and also chair, fence and mushrooms. In each of those cases, I think I'd always want a robot to go for the block first, with the item as an afterthought.

So I'm gonna change it so that these items have a special "either" condition, and when a robot is locating an item, they will try to find both - whichever's closest. For the autocomplete list, they'll be listed as blocks.

**Comment by TerryCavanagh** [comment]
Hmm, this seems to involve messing with the nav code at this point. Gonna split that bit into a new issue and leave that to you!
