### ISSUE TITLE
When a robot is told to moveto() one of the following items, treat blocks and items the same

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/autosurvive#72]
"Bed",
"Chest", 
"Shelter",	
"Workbench", 
"Sawmill", 
"Electronics Bench",
"Kiln", 
"Mushroom", 
"Fence", 
"Chair"

I.e, if a robot is told:

moveto(workbench);

then it moves to whichever is closer: the floating workbench item, or the stationary workbench.

**Comment by randomnine** [comment]
Seems to be working already

**Comment by TerryCavanagh** [comment]
Oh, great!
